### ISSUE TITLE
Needing a better understanding

### ISSUE THREAD

**Issue by bluewavenet** [mwarning/openwrt-examples#2]
@mwarning 
Thanks for this it helps a lot :-)
Comparing your examples with nodogsplash2, I am trying to understand the remote repository entries, particularly the following extracts from that package's Makefile and how the source files are picked up:
PKG_NAME:=nodogsplash2
PKG_FIXUP:=autoreconf
..
..
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)/
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=git://github.com/nodogsplash/nodogsplash.git
PKG_SOURCE_VERSION:=9d985d93f15db4052677dc34c37232bc958944bc
PKG_MIRROR_HASH:=12f9ea4e19c76f438f54a2214b098af233645713db7f8893c968fe1cab98ab1b
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
..
PKG_BUILD_PARALLEL:=1
..

**Comment by mwarning** [comment]
np :-)
The examples do not cover remote source examples, while this would be the common use case...

**Comment by bluewavenet** [comment]
@mwarning 
Many thanks again, your efforts are much appreciated :-)
