### ISSUE TITLE
sysupgrade

### ISSUE THREAD

**Issue by nusret3** [mwarning/openwrt-examples#5]
If the router already runs OpenWrt, then use the openwrt-*-sysupgrade.bin images. Transfer the image file to /tmp/ on the device (usually via scp <image> root@192.168.1.1:/tmp/) and use sysupgrade to apply the image:

sysupgrade /tmp/openwrt-*-sysupgrade.bin
Add -n to keep configuration files <------ adding -n does not keep configuration files. it overwrites instead!!! be careful

**Comment by mwarning** [comment]
Nice catch. Thanks! Fixed now.
