### ISSUE TITLE
can you review and add instructions to OpenWrt wiki?

### ISSUE THREAD

**Issue by stokito** [mwarning/openwrt-examples#7]
thank you for your instruction, it helped me a lot. I'm very happy that found your project because I wasn't able to build my package by following openwrt wiki instructions. 
Can you please add your notes and review the howtos? 
* https://openwrt.org/docs/guide-developer/build-system/use-buildsystem
* https://openwrt.org/docs/guide-developer/crosscompile
* https://openwrt.org/docs/guide-developer/packages

For example I added myself the trick with ```make -j`nproc` ``` but I'm not so experienced yet with other things

**Comment by mwarning** [comment]
Thank you for your kind words.

This repository is mostly a whiteboard for me to remember stuff I have learned and for others to peak into. Adding it to the OpenWrt wiki would be great, but also a great deal of work.

I do not have the time myself, but everybody is free to incorporate it into the OpenWrt wiki (I claim no authorship). It would be the obvious place for the content to be.
